#!/bin/bash

curl -v \
-H "X-Gitlab-Event: Push Event" \
-H "X-Gitlab-Token: makeyouruniquetokenongitlabandputithere-ezproxy" \
-H "Content-Type: application/json" \
-d '{"object_kind":"push","event_name":"push","before":"3ffb317a2a987e140b24e1fd84737e4497242edf","after":"71735651c54c050412f79db716719b361b02f6a1","ref":"refs/heads/master","checkout_sha":"71735651c54c050412f79db716719b361b02f6a1","message":null,"user_id":96,"user_name":"Example, Joe","user_email":"joe.example@example.com","user_avatar":"https://code.example.com/uploads/system/user/avatar/96/avatar.png","project_id":272,"project":{"name":"ezproxy","description":"Topic Search","web_url":"https://code.example.com/Library/ezproxy","avatar_url":null,"git_ssh_url":"git@code.example.com:Library/ezproxy.git","git_http_url":"https://code.example.com/Library/ezproxy.git","namespace":"Library","visibility_level":0,"path_with_namespace":"Library/ezproxy","default_branch":"master","homepage":"https://code.example.com/Library/ezproxy","url":"git@code.example.com:Library/ezproxy.git","ssh_url":"git@code.example.com:Library/ezproxy.git","http_url":"https://code.example.com/Library/ezproxy.git"},"commits":[{"id":"71735651c54c050412f79db716719b361b02f6a1","message":"Update post.js","timestamp":"2017-09-21T11:14:07-05:00","url":"https://code.example.com/Library/ezproxy/commit/71735651c54c050412f79db716719b361b02f6a1","author":{"name":"Example, Joe","email":"joe.example@example.com"},"added":[],"modified":["post.js"],"removed":[]}],"total_commits_count":1,"repository":{"name":"ezproxy","url":"git@code.example.com:Library/ezproxy.git","description":"Topic Search","homepage":"https://code.example.com/Library/ezproxy","git_http_url":"https://code.example.com/Library/ezproxy.git","git_ssh_url":"git@code.example.com:Library/ezproxy.git","visibility_level":0}}' http://localhost:9000/


# {"object_kind":"push","event_name":"push","before":"dbd13e233d86380d38f163788e241fc3c99f3770","after":"e98a045d7461c3ca0af9aaeb1fe1656ce66edbde","ref":"refs/heads/master","checkout_sha":"e98a045d7461c3ca0af9aaeb1fe1656ce66edbde","message":null,"user_id":96,"user_name":"Example, Joe","user_email":"joe.example@example.com","user_avatar":"https://code.example.com/uploads/system/user/avatar/96/avatar.png","project_id":279,"project":{"name":"ezproxy","description":"contains ezproxy configuration for auto-deploy to ezproxy-dev and ezproxy.example.com.","web_url":"https://code.example.com/Library/ezproxy","avatar_url":null,"git_ssh_url":"git@code.example.com:Library/ezproxy.git","git_http_url":"https://code.example.com/Library/ezproxy.git","namespace":"Library","visibility_level":0,"path_with_namespace":"Library/ezproxy","default_branch":"master","homepage":"https://code.example.com/Library/ezproxy","url":"git@code.example.com:Library/ezproxy.git","ssh_url":"git@code.example.com:Library/ezproxy.git","http_url":"https://code.example.com/Library/ezproxy.git"},"commits":[{"id":"e98a045d7461c3ca0af9aaeb1fe1656ce66edbde","message":"massive clean-up removed commented out stanzas.\nRemoved retired vendor site","timestamp":"2017-09-21T13:27:49-05:00","url":"https://code.example.com/Library/ezproxy/commit/e98a045d7461c3ca0af9aaeb1fe1656ce66edbde","author":{"name":"Example, Joe","email":"joe.example@example.com"},"added":[],"modified":["config.txt"],"removed":[]},{"id":"a57bba4aed153a2739fab6f9236f7dabcec3fc3b","message":"removed Journal ABC - commented out, no longer in use.","timestamp":"2017-09-20T15:57:04-05:00","url":"https://code.example.com/Library/ezproxy/commit/a57bba4aed153a2739fab6f9236f7dabcec3fc3b","author":{"name":"Example, Joe","email":"joe.example@example.com"},"added":[],"modified":["config.txt"],"removed":[]},{"id":"dbd12e233d86380d38f163788e241fc3c99f3770","message":"remove commented out advisoryboard","timestamp":"2017-09-20T15:54:44-05:00","url":"https://code.example.com/Library/ezproxy/commit/dbd12e233d86380d38f163788e241fc3c99f3770","author":{"name":"Example, Joe","email":"joe.example@example.com"},"added":[],"modified":["config.txt"],"removed":[]}],"total_commits_count":3,"repository":{"name":"ezproxy","url":"git@code.example.com:Library/ezproxy.git","description":"contains ezproxy configuration for auto-deploy to ezproxy-dev and ezproxy.example.com.","homepage":"https://code.example.com/Library/ezproxy","git_http_url":"https://code.example.com/Library/ezproxy.git","git_ssh_url":"git@code.example.com:Library/ezproxy.git","visibility_level":0}}
